# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1141, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/fundo2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 1001, 501))
        self.label_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 191); /* branco com 75% de opacidade */\n"
"    border: 2px solid rgba(255, 255, 255, 191); /* borda branca com 75% de opacidade */\n"
"    border-radius: 20px; /* borda arredondada */\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(580, 160, 381, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 380, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 370, 431, 101))
        self.label_3.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 431, 101))
        self.label_4.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 130, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 260, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 250, 431, 101))
        self.label_8.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 120, 431, 101))
        self.label_9.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(550, 130, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(550, 250, 431, 101))
        self.label_11.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 260, 431, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcular.setGeometry(QtCore.QRect(610, 400, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calcular.setFont(font)
        self.pushButton_calcular.setStyleSheet("QPushButton {\n"
"    background-color: rgb(100, 181, 246); /* azul claro */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(66, 165, 245); /* azul médio no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(33, 150, 243); /* azul mais escuro no clique */\n"
"}\n"
"")
        self.pushButton_calcular.setShortcut("")
        self.pushButton_calcular.setObjectName("pushButton_calcular")
        self.lineEdit_gasolina = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gasolina.setGeometry(QtCore.QRect(90, 170, 391, 31))
        self.lineEdit_gasolina.setObjectName("lineEdit_gasolina")
        self.lineEdit_gas = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gas.setGeometry(QtCore.QRect(90, 300, 391, 31))
        self.lineEdit_gas.setObjectName("lineEdit_gas")
        self.lineEdit_energia = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_energia.setGeometry(QtCore.QRect(90, 420, 391, 31))
        self.lineEdit_energia.setObjectName("lineEdit_energia")
        self.lineEdit_km = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_km.setGeometry(QtCore.QRect(570, 300, 391, 31))
        self.lineEdit_km.setObjectName("lineEdit_km")
        self.comboBox_transporte = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_transporte.setGeometry(QtCore.QRect(570, 170, 391, 31))
        self.comboBox_transporte.setObjectName("comboBox_transporte")
        self.comboBox_transporte.addItem("")
        self.comboBox_transporte.addItem("")
        self.comboBox_transporte.addItem("")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(90, 30, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30); /* leve brilho no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 60); /* leve brilho no clique */\n"
"}\n"
"")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(280, 10, 491, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.pushButton_calcular.raise_()
        self.lineEdit_gasolina.raise_()
        self.lineEdit_gas.raise_()
        self.lineEdit_energia.raise_()
        self.lineEdit_km.raise_()
        self.comboBox_transporte.raise_()
        self.pushButton_voltar.raise_()
        self.label_13.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Energia gasta (kWh)"))
        self.label_5.setText(_translate("MainWindow", "Gasolina gasta (litros)"))
        self.label_7.setText(_translate("MainWindow", "Gás gasto (m³)"))
        self.label_10.setText(_translate("MainWindow", "Meios de transporte"))
        self.label_12.setText(_translate("MainWindow", "Kilometros rodados(km/hr)"))
        self.pushButton_calcular.setText(_translate("MainWindow", "calcular"))
        self.comboBox_transporte.setItemText(0, _translate("MainWindow", "Carro"))
        self.comboBox_transporte.setItemText(1, _translate("MainWindow", "Moto"))
        self.comboBox_transporte.setItemText(2, _translate("MainWindow", "Onibus"))
        self.pushButton_voltar.setText(_translate("MainWindow", "⬅️"))
        self.label_13.setText(_translate("MainWindow", "insira os dados para calcular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
