# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 1061, 531))
        self.label_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 191); /* branco com 75% de opacidade */\n"
"    border: 2px solid rgba(255, 255, 255, 191); /* borda branca com 75% de opacidade */\n"
"    border-radius: 20px; /* borda arredondada */\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-80, -20, 1161, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/calculadoraBot.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 70, 421, 201))
        self.label_9.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gas = QtWidgets.QLabel(self.centralwidget)
        self.gas.setGeometry(QtCore.QRect(260, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gas.setFont(font)
        self.gas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gas.setObjectName("gas")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(1)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(110, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.arvore = QtWidgets.QLabel(self.centralwidget)
        self.arvore.setGeometry(QtCore.QRect(330, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arvore.setFont(font)
        self.arvore.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arvore.setObjectName("arvore")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 210, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.credit = QtWidgets.QLabel(self.centralwidget)
        self.credit.setGeometry(QtCore.QRect(450, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.credit.setFont(font)
        self.credit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.credit.setObjectName("credit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 90, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(540, 70, 501, 361))
        self.label_13.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(630, 50, 321, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(570, 190, 421, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(90, 310, 421, 201))
        self.label_16.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(110, 310, 381, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(160, 320, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(220, -40, 701, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.refazer = QtWidgets.QPushButton(self.centralwidget)
        self.refazer.setGeometry(QtCore.QRect(540, 440, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.refazer.setFont(font)
        self.refazer.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #4CAF50; /* verde */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* verde mais escuro no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* verde ainda mais escuro no clique */\n"
"}")
        self.refazer.setShortcut("")
        self.refazer.setObjectName("refazer")
        self.fechar = QtWidgets.QPushButton(self.centralwidget)
        self.fechar.setGeometry(QtCore.QRect(790, 440, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fechar.setFont(font)
        self.fechar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0); /* vermelho */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(236, 76, 76); /* vermelho mais claro no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(208, 11, 11); /* vermelho mais escuro no clique */\n"
"}\n"
"")
        self.fechar.setShortcut("")
        self.fechar.setObjectName("fechar")
        self.label.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.gas.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_8.raise_()
        self.arvore.raise_()
        self.label_10.raise_()
        self.credit.raise_()
        self.label_7.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.refazer.raise_()
        self.fechar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Você emitiu"))
        self.gas.setText(_translate("MainWindow", "a"))
        self.label_4.setText(_translate("MainWindow", "kg de CO₂ no total."))
        self.label_5.setText(_translate("MainWindow", "🔥"))
        self.label_8.setText(_translate("MainWindow", "🌳 Árvores necessárias:"))
        self.arvore.setText(_translate("MainWindow", "a"))
        self.label_10.setText(_translate("MainWindow", "♻️ Créditos de carbono equivalentes:"))
        self.credit.setText(_translate("MainWindow", "a"))
        self.label_7.setText(_translate("MainWindow", "resultados"))
        self.label_14.setText(_translate("MainWindow", "dicas de redução de consumo"))
        self.label_15.setText(_translate("MainWindow", "💡 Apague as luzes ao sair dos cômodos.   \n"
"\n"
"🚴‍♂️ Prefira transporte público ou bicicleta.   \n"
"\n"
"🥦 Reduza o consumo de carne vermelha.   \n"
"\n"
"🔌 Desligue aparelhos da tomada quando não estiver usando.  \n"
"\n"
"🌳 Plante uma árvore — pequenas ações somam!"))
        self.label_17.setText(_translate("MainWindow", "Cada pessoa no Brasil emite, em média, 11 toneladas de CO₂ por ano — cerca de 916 kg por mês.\n"
"Pequenas ações no dia a dia ajudam a diminuir essa pegada. 🌱"))
        self.label_18.setText(_translate("MainWindow", "🌎 Sabia disso?"))
        self.label_19.setText(_translate("MainWindow", "🌍 Relatório da sua pegada de carbono 🌿"))
        self.refazer.setText(_translate("MainWindow", "🔁 refazer calculo"))
        self.fechar.setText(_translate("MainWindow", "❌ fechar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
