# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-9, 0, 1151, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/calculadoraBot.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 1051, 531))
        self.label_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 191); /* branco com 75% de opacidade */\n"
"    border: 2px solid rgba(255, 255, 255, 191); /* borda branca com 75% de opacidade */\n"
"    border-radius: 20px; /* borda arredondada */\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 150, 321, 381))
        self.label_10.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.site2 = QtWidgets.QLabel(self.centralwidget)
        self.site2.setGeometry(QtCore.QRect(380, 150, 301, 181))
        self.site2.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(0, 0, 0, 0); /* totalmente transparente */")
        self.site2.setText("")
        self.site2.setScaledContents(False)
        self.site2.setAlignment(QtCore.Qt.AlignCenter)
        self.site2.setObjectName("site2")
        self.site3 = QtWidgets.QLabel(self.centralwidget)
        self.site3.setGeometry(QtCore.QRect(730, 150, 301, 181))
        self.site3.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(0, 0, 0, 0); /* totalmente transparente */")
        self.site3.setText("")
        self.site3.setScaledContents(False)
        self.site3.setAlignment(QtCore.Qt.AlignCenter)
        self.site3.setObjectName("site3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(720, 150, 321, 381))
        self.label_11.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 150, 321, 381))
        self.label_12.setStyleSheet("border-radius: 20px; \n"
" background-color:rgb(218, 218, 218);\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.site1 = QtWidgets.QLabel(self.centralwidget)
        self.site1.setGeometry(QtCore.QRect(50, 150, 291, 181))
        self.site1.setStyleSheet("border-radius: 20px;\n"
"background-color: rgba(0, 0, 0, 0); /* totalmente transparente */")
        self.site1.setText("")
        self.site1.setScaledContents(False)
        self.site1.setAlignment(QtCore.Qt.AlignCenter)
        self.site1.setObjectName("site1")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(110, -40, 881, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.link1 = QtWidgets.QLabel(self.centralwidget)
        self.link1.setGeometry(QtCore.QRect(70, 320, 231, 41))
        self.link1.setStyleSheet("")
        self.link1.setAlignment(QtCore.Qt.AlignCenter)
        self.link1.setObjectName("link1")
        self.link2 = QtWidgets.QLabel(self.centralwidget)
        self.link2.setGeometry(QtCore.QRect(410, 320, 231, 41))
        self.link2.setStyleSheet("")
        self.link2.setAlignment(QtCore.Qt.AlignCenter)
        self.link2.setObjectName("link2")
        self.link3 = QtWidgets.QLabel(self.centralwidget)
        self.link3.setGeometry(QtCore.QRect(760, 320, 231, 41))
        self.link3.setStyleSheet("")
        self.link3.setAlignment(QtCore.Qt.AlignCenter)
        self.link3.setObjectName("link3")
        self.textos1 = QtWidgets.QLabel(self.centralwidget)
        self.textos1.setGeometry(QtCore.QRect(50, 350, 291, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textos1.setFont(font)
        self.textos1.setStyleSheet("")
        self.textos1.setAlignment(QtCore.Qt.AlignCenter)
        self.textos1.setWordWrap(True)
        self.textos1.setObjectName("textos1")
        self.texto2 = QtWidgets.QLabel(self.centralwidget)
        self.texto2.setGeometry(QtCore.QRect(390, 350, 291, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.texto2.setFont(font)
        self.texto2.setStyleSheet("")
        self.texto2.setAlignment(QtCore.Qt.AlignCenter)
        self.texto2.setWordWrap(True)
        self.texto2.setObjectName("texto2")
        self.texto3 = QtWidgets.QLabel(self.centralwidget)
        self.texto3.setGeometry(QtCore.QRect(740, 350, 291, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.texto3.setFont(font)
        self.texto3.setStyleSheet("")
        self.texto3.setAlignment(QtCore.Qt.AlignCenter)
        self.texto3.setWordWrap(True)
        self.texto3.setObjectName("texto3")
        self.textoE = QtWidgets.QLabel(self.centralwidget)
        self.textoE.setGeometry(QtCore.QRect(80, 60, 951, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textoE.setFont(font)
        self.textoE.setText("")
        self.textoE.setAlignment(QtCore.Qt.AlignCenter)
        self.textoE.setWordWrap(True)
        self.textoE.setObjectName("textoE")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(20, 10, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 30); /* leve brilho no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 60); /* leve brilho no clique */\n"
"}\n"
"")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label.raise_()
        self.label_6.raise_()
        self.label_10.raise_()
        self.site2.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.site1.raise_()
        self.site3.raise_()
        self.label_19.raise_()
        self.link1.raise_()
        self.link2.raise_()
        self.link3.raise_()
        self.textos1.raise_()
        self.texto2.raise_()
        self.texto3.raise_()
        self.textoE.raise_()
        self.pushButton_voltar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "🌍   sites que falam sobre o consumo sustentavel 🌿"))
        self.link1.setText(_translate("MainWindow", "aaaaaa"))
        self.link2.setText(_translate("MainWindow", "aaaaaa"))
        self.link3.setText(_translate("MainWindow", "aaaaaa"))
        self.textos1.setText(_translate("MainWindow", "aaaaaa"))
        self.texto2.setText(_translate("MainWindow", "aaaaaa"))
        self.texto3.setText(_translate("MainWindow", "aaaaaa"))
        self.pushButton_voltar.setText(_translate("MainWindow", "⬅️"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
