# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -40, 1151, 591))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/fundo1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, -20, 511, 211))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 441, 431))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(30, 30, 30);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 440, 304, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #4CAF50; /* verde */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049; /* verde mais escuro no hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3e8e41; /* verde ainda mais escuro no clique */\n"
"}")
        self.pushButton.setShortcut("")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 451, 491))
        self.label_4.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 191); /* branco com 75% de opacidade */\n"
"    border: 2px solid rgba(255, 255, 255, 191); /* borda branca com 75% de opacidade */\n"
"    border-radius: 20px; /* borda arredondada */\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 20, 471, 141))
        self.label_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 191); /* branco com 75% de opacidade */\n"
"    border: 2px solid rgba(255, 255, 255, 191); /* borda branca com 75% de opacidade */\n"
"    border-radius: 20px; /* borda arredondada */\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Calculadora de credito de carbono"))
        self.label_3.setText(_translate("MainWindow", "A Calculadora de Carbono é uma ferramenta prática e acessível que ajuda você a entender o impacto ambiental das suas atividades diárias. Ao inserir informações sobre transporte, consumo de energia, alimentação e hábitos de consumo, você descobre sua pegada de carbono e recebe orientações para reduzir ou compensar suas emissões. Contribua para um futuro mais sustentável começando por conhecer o seu impacto hoje."))
        self.pushButton.setText(_translate("MainWindow", "iniciar calculo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
